/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module CA2_base (
  input sA,
  input A3,
  input A2,
  input A1,
  input A0,
  output CAS,
  output CA3,
  output CA2,
  output CA1,
  output CA0
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign CAS = ((A0 & sA) | (A1 & sA) | (A2 & sA) | (A3 & sA));
  assign s3 = ~ sA;
  assign s2 = ~ A2;
  assign s1 = ~ A1;
  assign s0 = ~ A0;
  assign CA3 = ((s0 & s1 & s2 & A3) | (A0 & ~ A3 & sA) | (A1 & ~ A3 & sA) | (A2 & ~ A3 & sA) | (A3 & s3));
  assign CA2 = ((A0 & s2 & sA) | (s0 & s1 & A2) | (A1 & s2 & sA) | (A2 & s3));
  assign CA1 = ((A0 & s1 & sA) | (s0 & A1) | (A1 & s3));
  assign CA0 = A0;
endmodule

module SUM (
  input X,
  input Y,
  input Cin,
  output Z,
  output Cout
);
  assign Z = ((X ^ Y) ^ Cin);
  assign Cout = (((X & Y) | (X & Cin)) | (Y & Cin));
endmodule

module SUMRES1 (
  input Ys,
  input Y3,
  input Y2,
  input Y1,
  input Y0,
  input X0,
  input X1,
  input X2,
  input X3,
  input Xs,
  input Cin,
  output Z2,
  output Z3,
  output ZS,
  output Z1,
  output Z0,
  output Cout,
  output Dbd
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire Cout_temp;
  wire s17;
  CA2_base CA2_base_i0 (
    .sA( Ys ),
    .A3( Y3 ),
    .A2( Y2 ),
    .A1( Y1 ),
    .A0( Y0 ),
    .CAS( s0 ),
    .CA3( s1 ),
    .CA2( s2 ),
    .CA1( s3 ),
    .CA0( s4 )
  );
  CA2_base CA2_base_i1 (
    .sA( Xs ),
    .A3( X3 ),
    .A2( X2 ),
    .A1( X1 ),
    .A0( X0 ),
    .CAS( s5 ),
    .CA3( s6 ),
    .CA2( s7 ),
    .CA1( s8 ),
    .CA0( s9 )
  );
  SUM SUM_i2 (
    .X( s9 ),
    .Y( s4 ),
    .Cin( Cin ),
    .Z( s10 ),
    .Cout( s11 )
  );
  SUM SUM_i3 (
    .X( s8 ),
    .Y( s3 ),
    .Cin( s11 ),
    .Z( s12 ),
    .Cout( s13 )
  );
  SUM SUM_i4 (
    .X( s7 ),
    .Y( s2 ),
    .Cin( s13 ),
    .Z( s14 ),
    .Cout( s15 )
  );
  SUM SUM_i5 (
    .X( s6 ),
    .Y( s1 ),
    .Cin( s15 ),
    .Z( s16 ),
    .Cout( Cout_temp )
  );
  SUM SUM_i6 (
    .X( s5 ),
    .Y( s0 ),
    .Cin( Cout_temp ),
    .Z( s17 ),
    .Cout( Dbd )
  );
  CA2_base CA2_base_i7 (
    .sA( s17 ),
    .A3( s16 ),
    .A2( s14 ),
    .A1( s12 ),
    .A0( s10 ),
    .CAS( ZS ),
    .CA3( Z3 ),
    .CA2( Z2 ),
    .CA1( Z1 ),
    .CA0( Z0 )
  );
  assign Cout = Cout_temp;
endmodule
